"""Transparency label builder.

Maps the scorer's chosen ``label_variant`` to the verbatim, plain-language label text
a reader would see on the platform. The three variants are defined in planning.md
("Transparency label variants") and are reproduced here exactly. The label changes with
the confidence level — different *text*, not just a different number — and the AI variant
is deliberately hedged (asymmetry of harm: never a flat accusation).
"""

# Verbatim variants — keep in sync with planning.md and the README label table.
LABELS = {
    "high_confidence_ai": {
        "title": "🤖 Likely AI-generated",
        "body": (
            "Our analysis found strong signals that this text was generated by AI. Both "
            "how it reads and its writing patterns point this way. This is an automated "
            "estimate, not a certainty — the creator can appeal if they believe it's wrong."
        ),
    },
    "uncertain": {
        "title": "❓ Origin unclear",
        "body": (
            "We couldn't confidently tell whether this text was written by a person or "
            "generated by AI. Our signals were weak or disagreed with each other, so "
            "we're not making a call. Treat this as undetermined."
        ),
    },
    "high_confidence_human": {
        "title": "✍️ Likely human-written",
        "body": (
            "Our analysis found strong signals that a person wrote this text. How it reads "
            "and its writing patterns are both consistent with human authorship. This is "
            "an automated estimate, not a guarantee."
        ),
    },
}


def build_label(label_variant, confidence):
    """Return the transparency label for a given variant key + confidence score.

    The numeric confidence is surfaced alongside the text for platforms that want it,
    but the human-readable text stands on its own.
    """
    variant = LABELS.get(label_variant, LABELS["uncertain"])
    return {
        "variant": label_variant,
        "title": variant["title"],
        "body": variant["body"],
        "confidence": confidence,
    }


def build_verified_label(certificate):
    """Verified-Human badge for the Provenance Certificate stretch feature.

    Deliberately distinct from the automated detection labels above: it is a green
    check-badge that vouches for the *creator* (who completed verification), not an
    estimate about the *text*. A reader sees it alongside — not instead of — the
    detection label, so the two sources of trust are never conflated.
    """
    return {
        "variant": "verified_human",
        "badge": "✅ Verified Human",
        "body": (
            "This creator completed Provenance Guard's human-verification step, so their "
            "authorship is confirmed — this is a verified credential, not an automated "
            "guess. Issued {issued}.".format(issued=certificate.get("issued_at", ""))
        ),
        "certificate_id": certificate.get("certificate_id"),
    }


if __name__ == "__main__":
    import json

    # Confirm all three variants render exactly as specified (M5 verification step).
    for key in ("high_confidence_ai", "uncertain", "high_confidence_human"):
        print(json.dumps(build_label(key, 0.0), indent=2, ensure_ascii=False))
