"""Signal 1 in the spec — the LLM semantic classifier (Groq `llama-3.3-70b-versatile`).

This signal judges *meaning and voice* holistically: does the text read as
authentically human, or does it have the flavorless, hedge-heavy, connective-tissue
quality of AI prose? It returns ``ai_score`` ∈ [0,1] (probability the text is AI) plus
a short rationale. See planning.md ("Detection signals" -> Signal 1) for what it
captures and its blind spots (notably a bias against formal / non-native writing).

The signal degrades gracefully: if no API key is configured or the call fails, it
returns ``available: False`` and the confidence scorer falls back to stylometry alone
(with capped confidence), rather than failing the whole request.
"""

import json
import os

from dotenv import load_dotenv

load_dotenv()

MODEL = "llama-3.3-70b-versatile"

# The prompt encodes the asymmetry-of-harm principle from planning.md: the model is
# told to err toward "human" when unsure, because a false AI accusation is the costlier
# error on a writing platform.
SYSTEM_PROMPT = """You are a forensic writing analyst estimating whether a passage was \
written by a human or generated by an AI language model.

Judge holistically from the *writing itself* — voice, specificity, emotional texture, \
and how natural the phrasing feels. Signals that lean AI: generic or hedged statements, \
formulaic transitions ("Moreover", "Furthermore", "It is important to note"), evenly \
balanced structure, and an absence of lived, concrete, idiosyncratic detail. Signals \
that lean human: specific personal detail, uneven emphasis, a distinct voice, and \
natural imperfection.

Be cautious: formal, academic, or non-native-English writing can look "AI-like" but is \
often genuinely human. When the evidence is weak or mixed, stay near 0.5 rather than \
committing — a confident false "AI" verdict is the worst outcome.

Respond with ONLY a JSON object of the form:
{"ai_probability": <number between 0 and 1>, "rationale": "<one concise sentence>"}
where ai_probability is your estimated probability the text was AI-generated."""


def _client():
    try:
        from groq import Groq
    except ImportError:
        return None
    key = os.environ.get("GROQ_API_KEY")
    if not key:
        return None
    return Groq(api_key=key)


def analyze_llm(text):
    client = _client()
    if client is None:
        return {
            "available": False,
            "ai_score": None,
            "rationale": "LLM signal unavailable (GROQ_API_KEY not set or groq not installed).",
        }
    try:
        resp = client.chat.completions.create(
            model=MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
            temperature=0,
            response_format={"type": "json_object"},
        )
        data = json.loads(resp.choices[0].message.content)
        score = max(0.0, min(1.0, float(data["ai_probability"])))
        rationale = str(data.get("rationale", "")).strip()[:300]
        return {"available": True, "ai_score": round(score, 3), "rationale": rationale}
    except Exception as e:  # network error, bad key, malformed JSON, etc.
        return {
            "available": False,
            "ai_score": None,
            "rationale": f"LLM signal error: {type(e).__name__}: {e}",
        }


if __name__ == "__main__":
    # Standalone verification (Milestone 4): run the signal on the same kinds of inputs
    # used for stylometry and eyeball that the scores move in the expected direction.
    samples = {
        "clearly_ai": (
            "Artificial intelligence represents a transformative paradigm shift in modern "
            "society. It is important to note that while the benefits of AI are numerous, "
            "it is equally essential to consider the ethical implications. Furthermore, "
            "stakeholders across various sectors must collaborate to ensure responsible "
            "deployment."
        ),
        "clearly_human": (
            "ok so i finally tried that new ramen place downtown and honestly? "
            "underwhelming. the broth was fine but they put WAY too much sodium in it and "
            "i was thirsty for like three hours after."
        ),
    }
    for name, txt in samples.items():
        print(f"\n=== {name} ===")
        print(json.dumps(analyze_llm(txt), indent=2))
